image: "python:3.6"

variables:
  REPO: gitlab.computing.dcu.ie
  GROUP: iidele
  PROJECT: 2021-ca400-idelegi2-puzzuos2

stages:
  - init
  - test
  - build

ai_poker_ci_start:
     tags:
       - ci
     script:
       - echo poker_ci_start job with test_ai_model.py running
