image: node:10.15.3

variables:
  REPO: gitlab.computing.dcu.ie
  GROUP: iidele
  PROJECT: 2021-ca400-idelegi2-puzzuos2

stages:
  - init
  - test
  - build

before_script:
  - cd src/ui
  - yarn install

cache:
  key: $CI_PROJECT_ID
  policy: pull
  untracked: true

init:
  stage: init
  image: node:10.15.3
  script: ['']

ai_poker-ci-start:
     tags:
       - ci
     script:
       - echo ai_poker_ci_start job with test_ai_model.py running

app-build:
  stage: build
  image: node:10.15.3
  script:
    - cd src
    - echo "Start building App..."
    - yarn build
    - echo "Build successful!"
  artifacts:
    paths:
      - 'packages/*/lib' 

frontend-test:
  stage: test
  image: node:10.15.3
  script:
    - cd src
    - echo "Testing front-end Components..."
    - yarn test
    - echo "Front-end Components rendered successfully!"
