image: python:latest


variables:
  REPO: gitlab.computing.dcu.ie
  GROUP: iidele
  PROJECT: 2021-ca400-idelegi2-puzzuos2
  # Change pip's cache directory to be inside the project directory since we can only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - init
  - test
  - build

cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - src/ui/node_modules
    - .cache/pip
    - venv/

before_script:
  - python -V               # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


ai_poker_ci_start:
     tags:
       - ci
     script:
       - echo ai_poker_ci_start job with test_ai_model.py running
