image: python:3.6

variables:
  REPO: gitlab.computing.dcu.ie
  GROUP: iidele
  PROJECT: 2021-ca400-idelegi2-puzzuos2

stages:
  - init
  - test
  - build

cache:
  key: ${CI_COMMIT_SHA}
  paths:
    - src/ui/node_modules

before_script:
  - cd src/test

init:
  stage: init
  image: node
  script: ['']
  cache:
    policy: pull-push
    key: ${CI_COMMIT_SHA}
    paths: ['src/ui/node_modules']


ai_poker_ci_start:
     tags:
       - ci
     script:
       - echo ai_poker_ci_start job with test_ai_model.py running

ai_poker_all_tests:
    stage: test
    script:
      - pip install -r requirements.txt
      - python -m unittest

frontend-build:
  stage: build
  image: node
  script:
    - cd ../ui/src
    - echo "Start building App..."
    - npm install -g yarn
    - yarn install
    - yarn build
    - echo "Build successful!"
