image: python:3.6


before_script:
  - cd src/tests
  - pip install -r requirements.txt


ai_poker_ci_start:
     tags:
       - ci
     script:
       - echo ai_poker_ci_start job with test_ai_model.py running
