image: node:10.15.3

cache:
  paths:
    - node_modules/
    - .yarn

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - init
  - test
  - build

init:
  stage: init
  image: node:10.15.3
  script: ['']

ai_poker-ci-start:
     tags:
       - ci
     script:
       - echo ai_poker_ci_start job with test_ai_model.py running

ai_poker-test:
    stage: test
    image: python:3.6
    script:
      - cd src/test
      - pip install -r requirements.txt
      - python -m unittest

app-build:
  stage: build
  image: node:10.15.3
  script:
    - cd src/ui/src
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
    - echo "Start building App..."
    - yarn build
    - echo "Build successful!"

frontend-test:
  stage: test
  image: node:10.15.3
  script:
    - cd src/ui/src
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
    - echo "Testing front-end Components..."
    - yarn test
    - echo "Front-end Components rendered successfully!"
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules/
